/*
    OpenAPI [ 01.10.2022 ] Georgi Angelov
    Position Independent Code - Shared Library
*/

    {"api_variable", &api_variable},
    {"api_constant", &api_constant},
    {"api_syscall", api_syscall},
    {"api_malloc", api_malloc},
    {"api_realloc", api_realloc},
    {"api_calloc", api_calloc},
    {"api_free", api_free},
    {"yield", yield},
    {"millis", millis},
    {"micros", micros},
    {"delay", delay},
    {"delayMicroseconds", delayMicroseconds},
    {"adcMode", adcMode},
    {"pwmMode", pwmMode},
    {"pinMode", pinMode},
    {"digitalRead", digitalRead},
    {"digitalWrite", digitalWrite},
    {"digitalToggle", digitalToggle},
    {"analogRead", analogRead},
    {"analogWrite", analogWrite},
    {"detachInterrupt", detachInterrupt},
    {"attachInterrupt", attachInterrupt},
    {"drv_create", drv_create},
    {"drv_free", drv_free},
    {"drv_open", drv_open},
    {"drv_close", drv_close},
    {"drv_read", drv_read},
    {"drv_write", drv_write},
    {"drv_syscall", drv_syscall},
